### ISSUE TITLE
1分，2分，5分的硬币，组成一元钱

### ISSUE THREAD

**Issue by ibigbug** [wazedix/algorithms#1]
有多少种组合

该怎么写？不是三重循环的话。

**Comment by wazedix** [comment]
1.因为确定了2种硬币的数量后，第三种可以算出来，因此可以简化为2重循环。
2.如果不用循环，就用深度优先搜索来枚举三种硬币的数量。思路和循环一样，只是这样能处理任意多种硬币的情况。
3.可以用动态规划。f[i][j] = f[i-1][j-value[i]]，i指的是第i种硬币，value[i]是第i种硬币的价值，j是面值，f[i][j]就是只用前i种硬币得到面值为j的组合数，最终答案是f[2][100]的值。动态规划就是记忆化搜索，可以理解为是第二种方法的缓存优化版。
4.issue好像不是这么用的吧...

**Comment by ibigbug** [comment]
能写demo 不。issue 怎么用，不太会用github 。

在 2013年5月17日星期五，wazedix 写道：

> 1.因为确定了2种硬币的数量后，第三种可以算出来，因此可以简化为2重循环。
> 2.如果不用循环，就用深度优先搜索来枚举三种硬币的数量。思路和循环一样，只是这样能处理任意多种硬币的情况。
> 3.可以用动态规划。f[i][j] =
> f[i-1][j-value[i]]，i指的是第i种硬币，value[i]是第i种硬币的价值，j是面值，f[i][j]就是只用前i种硬币得到面值为j的组合数，最终答案是f[2][100]的值。动态规划就是记忆化搜索，可以理解为是第二种方法的缓存优化版。
> 4.issue好像不是这么用的吧...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wazedix/algorithms/issues/1#issuecomment-18048345
> .

## 

发自移动版 Gmail

**Comment by wazedix** [comment]
动态规划：https://gist.github.com/wazedix/5598501
issue是用来报告某个项目的bug的吧

**Comment by ibigbug** [comment]
不知道，没项目没bug  。new  feathers 也可以吧

在 2013年5月17日星期五，wazedix 写道：

> 动态规划：https://gist.github.com/wazedix/5598501
> issue是用来报告某个项目的bug的吧
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wazedix/algorithms/issues/1#issuecomment-18056384
> .

## 

发自移动版 Gmail
